"""Render all Scene examples with D2 backend into renders/ folder."""

from plotcraft.scene import Scene

# 1. Pipeline
s = Scene(width=1200, height=500)
s.add("How a commit becomes a release", role="title")
s.add("Push Code", role="start")
s.add("Run Tests", role="process", emphasis="high")
s.add("Code Review", role="process")
s.add("Deploy", role="end")
s.connect("Push Code", "Run Tests")
s.connect("Run Tests", "Code Review")
s.connect("Code Review", "Deploy")
s.annotate("Automated CI", near="Run Tests")
s.annotate("Manual gate", near="Code Review")
s.add("Every step is automated, every gate must pass", role="caption")
s.layout("pipeline")
s.save("examples/renders/d2_pipeline.svg", engine="d2")
print("1. Pipeline done")

# 2. Fan-out
s = Scene(width=1100, height=600)
s.add("How events propagate", role="title")
s.add("Event Bus", role="start", size="large")
s.add("Logger", role="process")
s.add("Notifier", role="process", emphasis="high")
s.add("Archiver", role="process")
s.add("Analytics", role="process", emphasis="low")
s.connect("Event Bus", "Logger")
s.connect("Event Bus", "Notifier")
s.connect("Event Bus", "Archiver")
s.connect("Event Bus", "Analytics")
s.annotate("Real-time alerts", near="Notifier")
s.add("Every event reaches every consumer", role="caption")
s.layout("fan_out")
s.save("examples/renders/d2_fanout.svg", engine="d2")
print("2. Fan-out done")

# 3. Decision tree
s = Scene(width=1000, height=650)
s.add("Picking your database", role="title")
s.add("Structured?", role="decision", size="large")
s.add("PostgreSQL", role="end", size="large")
s.add("MongoDB", role="end", size="large")
s.connect("Structured?", "PostgreSQL", label="Yes")
s.connect("Structured?", "MongoDB", label="No")
s.annotate("ACID, joins, complex queries", near="PostgreSQL")
s.annotate("Flexible schema, rapid iteration", near="MongoDB")
s.add("Start simple, migrate when you outgrow it", role="caption")
s.layout("decision_tree")
s.save("examples/renders/d2_decision.svg", engine="d2")
print("3. Decision done")

# 4. Cycle
s = Scene(width=1000, height=700)
s.add("How AI agents think", role="title")
s.add("Observe", role="process", size="large", emphasis="high")
s.add("Think", role="decision")
s.add("Act", role="process", size="large")
s.connect("Observe", "Think")
s.connect("Think", "Act", label="execute")
s.connect("Act", "Observe", label="feedback", style="dashed")
s.annotate("Gather context", near="Observe")
s.annotate("Choose next action", near="Think")
s.add("Repeat until goal is reached", role="caption")
s.layout("cycle")
s.save("examples/renders/d2_cycle.svg", engine="d2")
print("4. Cycle done")

# 5. Dark theme top-down
s = Scene(dark=True)
s.add("The ML Pipeline", role="title")
s.add("Raw Data", role="start", size="large")
s.add("Preprocess", role="process", emphasis="high")
s.add("Train", role="process", size="large")
s.add("Evaluate", role="process")
s.add("Deploy", role="end", size="large")
s.connect("Raw Data", "Preprocess")
s.connect("Preprocess", "Train")
s.connect("Train", "Evaluate")
s.connect("Evaluate", "Deploy")
s.annotate("Clean, normalize", near="Preprocess")
s.annotate("GPU-accelerated", near="Train")
s.add("Iterate fast, deploy confidently", role="caption")
s.layout("top_down")
s.save("examples/renders/d2_dark.svg", engine="d2")
print("5. Dark done")

print("\nAll D2 renders in examples/renders/")
